version: '3.9'

services:
  app:
    build:
      context: .
    container_name: go_news_scraper_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
      DB_NAME: ${POSTGRES_DB:-postgres}
      DB_SSLMODE: "disable"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - news_scraper_net

  db:
    image: postgres:15
    container_name: go_news_scraper_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - news_scraper_net

volumes:
  postgres_data:

networks:
  news_scraper_net:
    driver: bridge